### ISSUE TITLE
:focus-within may drop some styles in IE 11 + Edge

### ISSUE THREAD

**Issue by jonnyscholes** [wagtail/react-streamfield#8]
I happened across this article today:

https://catalin.red/fancy-new-selectors-can-break-your-css-rule/

Yet to have a chance to test this, but we do use `:focus-within` in a couple of places in [c-sf-block.scss](https://github.com/noripyt/react-streamfield/blob/7c187d1ff6c1634de602a8a3312f88cc9c704e81/src/scss/components/c-sf-block.scss) so should consider using JS instead or at least forcing it to be a separate selector so it only drops the `:focus-within` styles and not the `:hover :focus` too.

**Comment by BertrandBordage** [comment]
Fixed by https://github.com/wagtail/react-streamfield/commit/78df5639066a8c5a697eb5f109c5d26566f481cc.
